services:
  wem.form_data_manager.backend.module.form_data_manager.listener.process_form_data:
    class: WEM\WEMFormDataManagerBundle\EventListener\ProcessFormDataListener
    arguments:
      $routingCandidates: '@contao.routing.candidates'
    public: true

  wem.form_data_manager.backend.module.form_data_manager.listener.compile_form_fields:
    class: WEM\WEMFormDataManagerBundle\EventListener\CompileFormFieldsListener
    public: true