services:
  _defaults:
    autoconfigure: true

  wem.data_container.form:
    class: WEM\WEMFormDataManagerBundle\DataContainer\Form
    public: true

  wem.data_container.form_storage:
    class: WEM\WEMFormDataManagerBundle\DataContainer\FormStorage
    arguments:
      $translator: '@contao.translation.translator'
    public: true

  wem.data_container.form_storage_data:
    class: WEM\WEMFormDataManagerBundle\DataContainer\FormStorageData
    arguments:
      $translator: '@contao.translation.translator'
    public: true

  wem.classes.dca.field.callback.load.tl_sm_form_storage_data.value:
    class: WEM\WEMFormDataManagerBundle\Classes\Dca\Field\Callback\LoadConditionnal
    arguments:
      $pdmCallback: '@wem.personal_data_manager.dca.field.callback.load'
      $frontendField: 'value'
      $table: 'tl_form_dtorage_data'
    public: true

  wem.classes.dca.field.callback.save.tl_sm_form_storage_data.value:
    class: WEM\WEMFormDataManagerBundle\Classes\Dca\Field\Callback\SaveConditionnal
    arguments:
      $pdmCallback: '@wem.personal_data_manager.dca.field.callback.save'
      $frontendField: 'value'
      $table: 'tl_form_dtorage_data'
    public: true

  wem.form_data_manager.listener.personal_data_ui:
    class: WEM\WEMFormDataManagerBundle\EventListener\PersonalDataManager\UiListener
    arguments:
      $translator: '@contao.translation.translator'
      $personalDataManagerUi: '@wem.personal_data_manager.service.personal_data_manager_ui'
    public: true

  wem.form_data_manager.listener.personal_data_csv_formatter:
    class: WEM\WEMFormDataManagerBundle\EventListener\PersonalDataManager\CsvFormatterListener
    arguments:
      $translator: '@contao.translation.translator'
    public: true

  wem.form_data_manager.listener.personal_data_export:
    class: WEM\WEMFormDataManagerBundle\EventListener\PersonalDataManager\ExportListener
    arguments:
      $translator: '@contao.translation.translator'
    public: true

  wem.form_data_manager.listener.personal_data_anonymize:
    class: WEM\WEMFormDataManagerBundle\EventListener\PersonalDataManager\AnonymizeListener
    arguments:
      $translator: '@contao.translation.translator'
    public: true

  wem.form_data_manager.listener.personal_data_manager:
    class: WEM\WEMFormDataManagerBundle\EventListener\PersonalDataManager\ManagerListener
    arguments:
      $translator: '@contao.translation.translator'
    public: true